services:
  - type: web
    name: immo-marly
    runtime: python
    pythonVersion: "3.11.0"
    buildCommand: pip install -r requirements.txt
    startCommand: python -m gunicorn app:app
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false